version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-3.3.15
    container_name: colonizzazioni_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table

  php:
    image: wodby/php:7.1-dev-4.11.8
    container_name: colonizzazioni_php
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./web:/var/www/html/risorse_omc

  apache:
    image: wodby/apache:latest
    container_name: colonizzazioni_apache
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/
    volumes:
      - ./docroot:/var/www/html
      - ./web:/var/www/html/risorse_omc
    ports:
      - "5000:80"
#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: colonizzazioni_pma
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    ports:
#      - '8090:80'
